name: DieselLinker CI/CD

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read
  id-token: write

concurrency:
  group: "diesel_linker-build-${{ github.ref }}"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # Augmente le timeout à 3 heures
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Docker Image
        run: docker build -t diesel_linker:latest .

      - name: Stop and Remove existing Docker container
        run: |
          if docker ps -a | grep -q diesel_linker; then
            docker stop diesel_linker
            docker rm diesel_linker
          else
            echo "No container to remove."
          fi

      - name: Run Docker Container and Build Project
        run: |
          docker run -d --name diesel_linker --memory 4g diesel_linker:latest
          echo "Container started, running cargo build..."
          docker exec diesel_linker cargo build --verbose

      - name: Run Tests in Docker Container
        run: |
          docker exec diesel_linker cargo test --verbose -- --test-threads=1

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # On met en cache les dépendances de Cargo pour accélérer le build
      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose